import { LoginButtons } from "@/components/loginButtons";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Image from "next/image";
import Link from "next/link";
import { UserDisplay } from "@/components/userDisplay";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-red-100 overflow-y-hidden`}>
        <nav className={"relative z-10 w-full box-border py-6 bg-red-200"}>
          <div className="flex justify-between items-center w-full relative">
            <div className="flex items-center z-10">
              <a href="/" className="absolute pl-4">
                <Image
                  src="/beef.png"
                  width={50}
                  height={50}
                  alt="Logo"
                  className="w-12 h-12 mr-2"
                />
              </a>
            </div>
            <div className="absolute w-full flex justify-center">
              <a
                href="/"
                className="text-2xl font-bold flex flex-col text-center"
              >
                <span className="text-sm">whats your</span>
                <span className="text-md">BEEF</span>
              </a>
            </div>
            <div className="text-lg md:text-xl flex flex-col md:flex-row md:gap-5 gap-1 z-10 px-4 text-right md:text-left font-bold">
              <UserDisplay />
              <LoginButtons />
            </div>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
